NAME = ft_display_file
FLAGS = -Wall -Werror -Wextra
SRC = src/ft_display_file.c

all: $(NAME)

$(NAME):
	gcc $(FLAGS) $(SRC) -o $(NAME)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean all